# -*- coding: utf-8 -*-
"""Statistic_HW0223

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyAgzi8oGji0ENVCnemznEgpuX2VI7Qv
"""

#按執行會有圖表
import numpy as np
import matplotlib.pyplot as plt

p = 0.5            #成功機率
iterations = 10000  #模擬實驗重複一萬次
sample_sizes = [5, 10, 50]  #測試三種不同的樣本量

plt.figure(figsize=(15, 5))  #圖表大小

for i, n in enumerate(sample_sizes):
    samples = np.random.binomial(1, p, (iterations, n))  #模擬Bernouli trial
    sample_means = np.mean(samples, axis=1)  #計算平均

    plt.subplot(1, 3, i+1)
    plt.hist(sample_means, bins=20, color='lightgreen', edgecolor='black', density=True)
    plt.title(f'Sample Size n = {n}')
    plt.xlabel('Sample Mean')
    plt.ylabel('Density')
    plt.xlim(-0.1, 1.1)  # 固定 X 軸範圍方便觀察

plt.tight_layout()
plt.show()