# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMwFc93-RnzLOFEmJviHb4nV1xBp7bHE
"""

import numpy as np  # 產生隨機數字
import matplotlib.pyplot as plt  # 圖表
from scipy.stats import norm  # 畫出標準的鐘形曲線

# 實驗次數
num_experiments = 10000

# 每次實驗丟骰子次數
sample_size = 50

#1. 生成許多把骰子的平均數
#numpy.random.randint(1, 7, size=(...)) 會生成一個 1 到 6 的隨機整數矩陣
#列:50 欄:10,000 排
# .mean(axis=1) 每行平均值
means = np.random.randint(1, 7, size=(num_experiments, sample_size)).mean(axis=1)

# 2. 畫圖
# 設定圖表的大小
plt.figure(figsize=(10, 6))
# 畫直方圖: 平均值/分類/總面積等於 1/透明度/藍色/圖表名字
# density=True 這樣可以跟「鐘形曲線」做比較。
plt.hist(means, bins=40, density=True, alpha=0.6, color='b', label='sample mean')

# 3. 鐘形曲線
#  fit 找到實驗結果的平均數 (mu) 和標準差 (std)
mu, std = norm.fit(means)
# x軸上最小值/最大值/點的數量
x = np.linspace(min(means), max(means), 100)
# 畫出標準的鐘形曲線/紅色
plt.plot(x, norm.pdf(x, mu, std), 'r-', label='C.L.T')

# 4. 加工圖表
plt.title(f'C.L.T\n(numofexp: {num_experiments} ; throw {sample_size} times each)')  # 標題
plt.xlabel('sample mean')  # x 軸
plt.ylabel('probability density')  # y 軸
plt.legend()  # 顯示右上角
plt.grid(axis='y', alpha=0.5)  # 格線

# 5. 顯示圖表
plt.show()

